version: '3.8'

services:
  verdaccio:
    container_name: verdaccio
    image: verdaccio/verdaccio
    ports:
      - 4873:4873
    volumes:
      - ./verdaccio:/verdaccio/storage
    restart: always
