version: '3.8'

services:
  mongo-db:
    container_name: mongodb
    image: mongo:5.0.6-focal
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27011:27017
    networks:
      - mongo-network

  mongo-express:
    container_name: mongo-ui
    image: mongo-express:1.0.0-alpha.4
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
    # ports:
    #   - 8080:8081
    ports:
      - 8001:8081
    networks:
      - mongo-network
    depends_on:
      - mongo-db


networks:
  mongo-network:
    driver: bridge
